<a href="https://colab.research.google.com/github/sreedharsiddhu/Project_ML-/blob/main/Working_project_ML_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [ ]:
Airport1 = pd.read_excel("/content/Grazzanise airport.xlsx")

In [ ]:
Airport2 = pd.read_excel("/content/Trapani airport.xlsx")

In [ ]:
Airport3 = pd.read_excel("/content/Treviso airport.xlsx")

In [ ]:
Airport1

,date,idstazione,lon,lat,altezza,pressure,three_hour_pressure_change,char_pressure_tendency,wind_direction,wind_speed,relative_humidity,visibility,present_weather,past_weather1,past_weather2,cloud_cover,height_of_base_of_cloud,cloud_type,drybulb,dewpoint
0,14/03/1996 12:00,16253,14.07,41.05,10,100790.0,20.0,0.0,70.0,7.7752,NaN,15000.0,2.0,1.0,1.0,6.0,1750.0,35,NaN,NaN
1,16/01/1997 18:00,16253,14.07,41.05,10,102290.0,20.0,3.0,0.0,0.0000,NaN,1800.0,10.0,0.0,0.0,1.0,800.0,31,NaN,NaN
2,19/06/1997 06:00,16253,14.07,41.05,10,100850.0,-380.0,6.0,0.0,0.0000,NaN,4500.0,10.0,1.0,1.0,6.0,800.0,38,NaN,NaN
3,30/05/1998 18:00,16253,14.07,41.05,10,101520.0,10.0,0.0,260.0,5.8314,NaN,20000.0,2.0,1.0,1.0,4.0,3500.0,30,NaN,NaN
4,15/12/1998 21:00,16253,14.07,41.05,10,102580.0,60.0,1.0,100.0,3.8876,NaN,8000.0,10.0,0.0,0.0,0.0,NaN,62,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69186,17/11/2023 19:00,16253,14.08,41.06,10,101060.0,60.0,3.0,280.0,1.9438,NaN,11000.0,2.0,1.0,1.0,3.0,3500.0,30,15.25,12.75
69187,17/11/2023 20:00,16253,14.08,41.06,10,101100.0,70.0,3.0,300.0,3.8876,NaN,11000.0,2.0,1.0,1.0,3.0,3500.0,30,14.65,12.55
69188,17/11/2023 21:00,16253,14.08,41.06,10,101190.0,110.0,2.0,320.0,5.8314,NaN,11000.0,2.0,1.0,1.0,3.0,800.0,31,13.85,11.75
69189,17/11/2023 22:00,16253,14.08,41.06,10,101220.0,160.0,2.0,350.0,7.7752,NaN,11000.0,2.0,1.0,1.0,2.0,3500.0,30,13.45,11.35
69190,17/11/2023 23:00,16253,14.08,41.06,10,101310.0,210.0,2.0,10.0,11.6628,NaN,11000.0,2.0,1.0,1.0,0.0,NaN,62,13.05,5.45

In [ ]:
Airport2

,date,idstazione,lon,lat,altezza,pressure,three_hour_pressure_change,char_pressure_tendency,wind_direction,wind_speed,relative_humidity,visibility,present_weather,past_weather1,past_weather2,cloud_cover,height_of_base_of_cloud,cloud_type,drybulb,dewpoint
0,01/01/1996 00:00,16429,12.50,37.92,9,100270.0,70.0,1.0,270.0,15.5504,NaN,10000.0,2.0,1.0,1.0,5.0,450.0,35,NaN,NaN
1,01/01/1996 03:00,16429,12.50,37.92,9,100280.0,10.0,3.0,270.0,17.4942,NaN,10000.0,2.0,1.0,1.0,4.0,250.0,35,NaN,NaN
2,01/01/1996 06:00,16429,12.50,37.92,9,100310.0,30.0,3.0,270.0,13.6066,NaN,14000.0,2.0,1.0,1.0,2.0,450.0,35,NaN,NaN
3,01/01/1996 09:00,16429,12.50,37.92,9,100490.0,180.0,1.0,270.0,9.7190,NaN,18000.0,2.0,1.0,1.0,3.0,800.0,35,NaN,NaN
4,01/01/1996 12:00,16429,12.50,37.92,9,100520.0,30.0,0.0,280.0,13.6066,NaN,18000.0,2.0,1.0,1.0,6.0,800.0,35,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175661,18/11/2023 19:00,16429,12.49,37.91,9,102320.0,180.0,1.0,100.0,3.8876,NaN,12000.0,2.0,1.0,1.0,0.0,NaN,62,14.05,9.15
175662,18/11/2023 20:00,16429,12.49,37.91,9,102350.0,170.0,1.0,90.0,3.8876,NaN,12000.0,2.0,1.0,1.0,0.0,NaN,62,13.85,8.85
175663,18/11/2023 21:00,16429,12.49,37.91,9,102390.0,180.0,1.0,110.0,3.8876,NaN,12000.0,2.0,1.0,1.0,0.0,NaN,62,12.25,8.95
175664,18/11/2023 22:00,16429,12.49,37.91,9,102390.0,70.0,1.0,130.0,1.9438,NaN,12000.0,2.0,1.0,1.0,0.0,NaN,62,11.85,9.05
175665,18/11/2023 23:00,16429,12.49,37.91,9,102380.0,30.0,1.0,150.0,1.9438,NaN,12000.0,2.0,1.0,1.0,0.0,NaN,62,12.05,10.15

In [ ]:
Airport3

,date,idstazione,lon,lat,altezza,pressure,three_hour_pressure_change,char_pressure_tendency,wind_direction,wind_speed,relative_humidity,visibility,present_weather,past_weather1,past_weather2,cloud_cover,height_of_base_of_cloud,cloud_type,drybulb,dewpoint
0,01/01/1996 00:00,16098,12.10,45.68,42,99090.0,100.0,2.0,10.0,5.8314,NaN,4000.0,10.0,6.0,5.0,8.0,800.0,37,NaN,NaN
1,01/01/1996 03:00,16098,12.10,45.68,42,99210.0,120.0,2.0,0.0,1.9438,NaN,3000.0,50.0,5.0,2.0,8.0,450.0,37,NaN,NaN
2,01/01/1996 06:00,16098,12.10,45.68,42,99330.0,120.0,2.0,20.0,1.9438,NaN,2500.0,60.0,6.0,5.0,8.0,450.0,37,NaN,NaN
3,01/01/1996 09:00,16098,12.10,45.68,42,NaN,NaN,NaN,0.0,1.9438,NaN,2500.0,NaN,NaN,NaN,8.0,NaN,62,NaN,NaN
4,01/01/1996 12:00,16098,12.10,45.68,42,99640.0,20.0,1.0,40.0,5.8314,NaN,8000.0,10.0,6.0,2.0,8.0,800.0,35,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174107,18/11/2023 19:00,16098,12.11,45.68,42,101760.0,10.0,1.0,10.0,5.8314,NaN,15000.0,2.0,1.0,1.0,1.0,2250.0,30,5.65,3.05
174108,18/11/2023 20:00,16098,12.11,45.68,42,101830.0,60.0,2.0,360.0,1.9438,NaN,15000.0,2.0,1.0,1.0,0.0,NaN,62,4.85,2.55
174109,18/11/2023 21:00,16098,12.11,45.68,42,101800.0,100.0,2.0,80.0,3.8876,NaN,15000.0,2.0,1.0,1.0,1.0,8000.0,30,4.45,2.15
174110,18/11/2023 22:00,16098,12.11,45.68,42,101800.0,40.0,3.0,120.0,1.9438,NaN,15000.0,2.0,1.0,1.0,0.0,NaN,62,3.65,2.05
174111,18/11/2023 23:00,16098,12.11,45.68,42,101770.0,-70.0,8.0,10.0,1.9438,NaN,15000.0,2.0,1.0,1.0,0.0,NaN,62,3.05,1.55

Finding the missing Values in Airport 1

In [ ]:

# Count the total number of missing values in Airport1
total_missing = Airport1.isnull().sum().sum()
print(f"Total missing values in Airport1: {total_missing}")

# Count the number of missing values for each column
missing_values_per_column = Airport1.isnull().sum()
print("\nMissing values per column in Airport1:")
print(missing_values_per_column)

# Get a boolean DataFrame indicating the location of missing values
missing_value_locations = Airport1.isnull()

Total missing values in Airport1: 157463

Missing values per column in Airport1:
date                              0
idstazione                        0
lon                               0
lat                               0
altezza                           0
pressure                         29
three_hour_pressure_change      216
char_pressure_tendency         2818
wind_direction                   40
wind_speed                       40
relative_humidity             69191
visibility                       21
present_weather                  35
past_weather1                    40
past_weather2                    42
cloud_cover                      64
height_of_base_of_cloud       17669
cloud_type                        0
drybulb                       33632
dewpoint                      33626
dtype: int64

Finding the missing values in Airport 2

In [ ]:
# Count the total number of missing values in Airport2
total_missing = Airport2.isnull().sum().sum()
print(f"Total missing values in Airport2: {total_missing}")

# Count the number of missing values for each column
missing_values_per_column = Airport2.isnull().sum()
print("\nMissing values per column in Airport2:")
print(missing_values_per_column)

# Get a boolean DataFrame indicating the location of missing values
missing_value_locations = Airport2.isnull()

Total missing values in Airport2: 410225

Missing values per column in Airport2:
date                               0
idstazione                         0
lon                                0
lat                                0
altezza                            0
pressure                         162
three_hour_pressure_change       343
char_pressure_tendency          3166
wind_direction                    63
wind_speed                        64
relative_humidity             175664
visibility                        23
present_weather                  115
past_weather1                    124
past_weather2                    119
cloud_cover                       57
height_of_base_of_cloud        36592
cloud_type                         0
drybulb                        96866
dewpoint                       96867
dtype: int64

Finding the missing values in Airport 3

In [ ]:
# Count the total number of missing values in Airport3
total_missing = Airport3.isnull().sum().sum()
print(f"Total missing values in Airport2: {total_missing}")

# Count the number of missing values for each column
missing_values_per_column = Airport3.isnull().sum()
print("\nMissing values per column in Airport3:")
print(missing_values_per_column)

# Get a boolean DataFrame indicating the location of missing values
missing_value_locations = Airport3.isnull()

Total missing values in Airport2: 428951

Missing values per column in Airport3:
date                               0
idstazione                         0
lon                                0
lat                                0
altezza                            0
pressure                          94
three_hour_pressure_change       250
char_pressure_tendency          3095
wind_direction                    63
wind_speed                        63
relative_humidity             174112
visibility                        41
present_weather                  177
past_weather1                    185
past_weather2                    187
cloud_cover                     1563
height_of_base_of_cloud        55206
cloud_type                         0
drybulb                        96957
dewpoint                       96958
dtype: int64

Finding the missing values of Airport 1 in Percentage

In [ ]:
# Count the number of missing values for each column
missing_values_count = Airport1.isnull().sum()

# Calculate the percentage of missing values for each column
total_rows = len(Airport1)
missing_values_percentage = (missing_values_count / total_rows) * 100

# Create a DataFrame to display the results
missing_values_df = pd.DataFrame({
    'Column': missing_values_count.index,
    'Missing Values': missing_values_count.values,
    'Percentage': missing_values_percentage.values
})

# Sort the DataFrame by the 'Percentage' column in descending order
missing_values_df = missing_values_df.sort_values(by='Percentage', ascending=False)

# Display the results
print(missing_values_df)

                        Column  Missing Values  Percentage
10           relative_humidity           69191  100.000000
18                     drybulb           33632   48.607478
19                    dewpoint           33626   48.598806
16     height_of_base_of_cloud           17669   25.536558
7       char_pressure_tendency            2818    4.072784
6   three_hour_pressure_change             216    0.312179
15                 cloud_cover              64    0.092498
14               past_weather2              42    0.060702
8               wind_direction              40    0.057811
9                   wind_speed              40    0.057811
13               past_weather1              40    0.057811
12             present_weather              35    0.050585
5                     pressure              29    0.041913
11                  visibility              21    0.030351
2                          lon               0    0.000000
17                  cloud_type               0    0.000000
3                          lat               0    0.000000
4                      altezza               0    0.000000
1                   idstazione               0    0.000000
0                         date               0    0.000000

Finding the missing values of Airport 2 in Percentage

In [ ]:
# Count the number of missing values for each column
missing_values_count = Airport2.isnull().sum()

# Calculate the percentage of missing values for each column
total_rows = len(Airport2)
missing_values_percentage = (missing_values_count / total_rows) * 100

# Create a DataFrame to display the results
missing_values_df = pd.DataFrame({
    'Column': missing_values_count.index,
    'Missing Values': missing_values_count.values,
    'Percentage': missing_values_percentage.values
})

# Sort the DataFrame by the 'Percentage' column in descending order
missing_values_df = missing_values_df.sort_values(by='Percentage', ascending=False)

# Display the results
print(missing_values_df)

                        Column  Missing Values  Percentage
10           relative_humidity          175664   99.998861
19                    dewpoint           96867   55.142714
18                     drybulb           96866   55.142145
16     height_of_base_of_cloud           36592   20.830440
7       char_pressure_tendency            3166    1.802284
6   three_hour_pressure_change             343    0.195257
5                     pressure             162    0.092220
13               past_weather1             124    0.070589
14               past_weather2             119    0.067742
12             present_weather             115    0.065465
9                   wind_speed              64    0.036433
8               wind_direction              63    0.035864
15                 cloud_cover              57    0.032448
11                  visibility              23    0.013093
17                  cloud_type               0    0.000000
2                          lon               0    0.000000
3                          lat               0    0.000000
1                   idstazione               0    0.000000
4                      altezza               0    0.000000
0                         date               0    0.000000

Finding the missing values of Airport 3 in Percentage

In [ ]:
# Count the number of missing values for each column
missing_values_count = Airport3.isnull().sum()

# Calculate the percentage of missing values for each column
total_rows = len(Airport3)
missing_values_percentage = (missing_values_count / total_rows) * 100

# Create a DataFrame to display the results
missing_values_df = pd.DataFrame({
    'Column': missing_values_count.index,
    'Missing Values': missing_values_count.values,
    'Percentage': missing_values_percentage.values
})

# Sort the DataFrame by the 'Percentage' column in descending order
missing_values_df = missing_values_df.sort_values(by='Percentage', ascending=False)

# Display the results
print(missing_values_df)

                        Column  Missing Values  Percentage
10           relative_humidity          174112  100.000000
19                    dewpoint           96958   55.687144
18                     drybulb           96957   55.686570
16     height_of_base_of_cloud           55206   31.707177
7       char_pressure_tendency            3095    1.777591
15                 cloud_cover            1563    0.897698
6   three_hour_pressure_change             250    0.143586
14               past_weather2             187    0.107402
13               past_weather1             185    0.106253
12             present_weather             177    0.101659
5                     pressure              94    0.053988
8               wind_direction              63    0.036184
9                   wind_speed              63    0.036184
11                  visibility              41    0.023548
17                  cloud_type               0    0.000000
2                          lon               0    0.000000
3                          lat               0    0.000000
1                   idstazione               0    0.000000
4                      altezza               0    0.000000
0                         date               0    0.000000

Summery of the Airport 1

In [ ]:


# Get summary statistics
summary = Airport1.describe()
print(summary)

       idstazione           lon           lat  altezza       pressure  \
count     69191.0  69191.000000  69191.000000  69191.0   69162.000000
mean      16253.0     14.071717     41.051717     10.0  101446.042914
std           0.0      0.003772      0.003772      0.0     670.824758
min       16253.0     14.070000     41.050000     10.0   97900.000000
25%       16253.0     14.070000     41.050000     10.0  101090.000000
50%       16253.0     14.070000     41.050000     10.0  101450.000000
75%       16253.0     14.070000     41.050000     10.0  101820.000000
max       16253.0     14.080000     41.060000     10.0  103910.000000

       three_hour_pressure_change  char_pressure_tendency  wind_direction  \
count                68975.000000            66373.000000    69151.000000
mean                     2.892787                4.280159      145.339764
std                     95.335549                2.537008      116.998655
min                   -690.000000                0.000000        0.000000
25%                    -50.000000                2.000000       40.000000
50%                      0.000000                4.000000      110.000000
75%                     50.000000                7.000000      250.000000
max                   1030.000000                8.000000      360.000000

         wind_speed  relative_humidity    visibility  present_weather  \
count  69151.000000                0.0  69170.000000     69156.000000
mean       5.797078                NaN  13989.064623         8.318599
std        4.060721                NaN   7264.649722        16.410110
min        0.000000                NaN     50.000000         1.000000
25%        3.887600                NaN  10000.000000         2.000000
50%        5.831400                NaN  14000.000000         2.000000
75%        7.775200                NaN  20000.000000        10.000000
max      103.021000                NaN  75000.000000        99.000000

       past_weather1  past_weather2   cloud_cover  height_of_base_of_cloud  \
count   69151.000000   69149.000000  69127.000000             51522.000000
mean        1.810603       1.278008      3.533540              1711.598152
std         2.108923       1.139510      2.808543              2095.770095
min         0.000000       0.000000      0.000000                30.000000
25%         1.000000       1.000000      1.000000               800.000000
50%         1.000000       1.000000      3.000000               800.000000
75%         1.000000       1.000000      6.000000              1750.000000
max         9.000000       9.000000      8.000000              8000.000000

         cloud_type       drybulb      dewpoint
count  69191.000000  35559.000000  35565.000000
mean      40.199376     16.610924     11.704199
std       12.829999      7.614871      7.198172
min       30.000000     -4.949990    -29.950000
25%       31.000000     11.050000      6.950000
50%       34.000000     16.050000     11.850000
75%       39.000000     22.050000     17.050000
max       62.000000     39.450000     32.350000

Summery of the Airport 2

In [ ]:

# Get summary statistics
summary = Airport2.describe()
print(summary)

       idstazione            lon            lat   altezza       pressure  \
count    175666.0  175666.000000  175666.000000  175666.0  175504.000000
mean      16429.0      12.499319      37.919319       9.0  101489.719437
std           0.0       0.002520       0.002520       0.0     596.142359
min       16429.0      12.490000      37.910000       9.0   90660.000000
25%       16429.0      12.500000      37.920000       9.0  101170.000000
50%       16429.0      12.500000      37.920000       9.0  101490.000000
75%       16429.0      12.500000      37.920000       9.0  101810.000000
max       16429.0      12.500000      37.920000       9.0  107100.000000

       three_hour_pressure_change  char_pressure_tendency  wind_direction  \
count               175323.000000           172500.000000   175603.000000
mean                     2.678599                4.099107      191.033399
std                     93.044439                2.561327      113.307126
min                  -1040.000000                0.000000        0.000000
25%                    -50.000000                2.000000      120.000000
50%                     10.000000                4.000000      170.000000
75%                     60.000000                6.000000      300.000000
max                   1070.000000                8.000000      500.000000

          wind_speed  relative_humidity     visibility  present_weather  \
count  175602.000000                2.0  175643.000000    175551.000000
mean        8.011608               63.0   15599.350102         5.980621
std         5.961997                0.0    4627.216804        14.475209
min         0.000000               63.0      30.000000         0.000000
25%         3.887600               63.0   12000.000000         2.000000
50%         7.775200               63.0   15000.000000         2.000000
75%        11.662800               63.0   20000.000000         2.000000
max       320.727000               63.0   75000.000000        99.000000

       past_weather1  past_weather2    cloud_cover  height_of_base_of_cloud  \
count  175542.000000  175547.000000  175609.000000            139074.000000
mean        1.554716       1.217856       3.463370              1335.546615
std         1.699310       0.924737       2.592045              1877.726271
min         0.000000       0.000000       0.000000                30.000000
25%         1.000000       1.000000       1.000000               450.000000
50%         1.000000       1.000000       3.000000               800.000000
75%         1.000000       1.000000       6.000000               800.000000
max        20.000000      19.000000       8.000000              8000.000000

          cloud_type       drybulb      dewpoint
count  175666.000000  78800.000000  78799.000000
mean       39.321047     18.389478     14.205437
std        11.768341      6.446896      5.715026
min        17.000000      1.050000    -29.950000
25%        32.000000     13.450000     10.050000
50%        35.000000     17.850000     13.850000
75%        38.000000     23.250000     18.650000
max        62.000000     60.050000     48.950000

Summery of the Airport 3

In [ ]:
# Get summary statistics
summary = Airport3.describe()
print(summary)

       idstazione            lon           lat   altezza       pressure  \
count    174112.0  174112.000000  1.741120e+05  174112.0  174018.000000
mean      16098.0      12.100687  4.568000e+01      42.0  101099.900413
std           0.0       0.002529  2.131634e-14       0.0     751.521598
min       16098.0      12.100000  4.568000e+01      42.0   97050.000000
25%       16098.0      12.100000  4.568000e+01      42.0  100670.000000
50%       16098.0      12.100000  4.568000e+01      42.0  101100.000000
75%       16098.0      12.100000  4.568000e+01      42.0  101560.000000
max       16098.0      12.110000  4.568000e+01      42.0  107030.000000

       three_hour_pressure_change  char_pressure_tendency  wind_direction  \
count               173862.000000           171017.000000   174049.000000
mean                     1.822307                4.302338      107.155652
std                    107.115723                2.661734      112.976549
min                  -3890.000000                0.000000        0.000000
25%                    -60.000000                2.000000       10.000000
50%                      0.000000                4.000000       60.000000
75%                     60.000000                7.000000      180.000000
max                   1000.000000                8.000000      500.000000

          wind_speed  relative_humidity     visibility  present_weather  \
count  174049.000000                0.0  174071.000000    173935.000000
mean        3.966715                NaN   12942.608648        11.214845
std         3.324492                NaN    9105.024618        18.725528
min         0.000000                NaN      30.000000         0.000000
25%         1.943800                NaN    6000.000000         2.000000
50%         3.887600                NaN   10000.000000         2.000000
75%         5.831400                NaN   16000.000000        10.000000
max       157.448000                NaN   75000.000000        99.000000

       past_weather1  past_weather2    cloud_cover  height_of_base_of_cloud  \
count  173927.000000  173925.000000  172549.000000            118906.000000
mean        1.891794       1.480149       3.795038              2255.493247
std         2.067999       1.407090       3.072375              2404.431196
min         0.000000       0.000000       0.000000                30.000000
25%         1.000000       1.000000       0.000000               800.000000
50%         1.000000       1.000000       4.000000              1250.000000
75%         2.000000       2.000000       7.000000              3500.000000
max         9.000000       9.000000       8.000000              8000.000000

          cloud_type       drybulb      dewpoint
count  174112.000000  77155.000000  77154.000000
mean       41.707016     14.417406      9.626815
std        13.886508      8.463814      7.441474
min        30.000000     -8.750000    -29.950000
25%        30.000000      7.850000      4.050000
50%        35.000000     14.050000      9.850000
75%        62.000000     20.850000     15.650000
max        62.000000     55.050000     29.650000